version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/products_reviews_db
